default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :test do
    xctest scheme: 'Buildkite Fastlane Demo',
           sdk: 'iphonesimulator',
           destination: 'platform=iOS Simulator,name=iPhone 6,OS=9.2',
           derivedDataPath: './fastlane/xcodebuild-data'
  end
end
